### ISSUE TITLE
Unable to compile getting error "WebServer.h: No such file or directory"

### ISSUE THREAD

**Issue by vjkanth** [igorantolic/esp32-alexa-wemo-emulator#2]
Using <a href="https://www.aliexpress.com/item/ESP32-wemos-ESP32-WiFi-Modules-Bluetooth-Dual-ESP-32-ESP-32S-ESP8266/32820262489.html">ESP32</a> on Windows 10 PC, connected via USB, able to flash it with simple programs and monitor serial port. Trying to upload this emulator but not compiling. Getting "WebServer.h: No such file or directory". Appears this is not supplied officially and there are many individual implementations. Any guidance on what to use?

**Comment by igorantolic** [comment]
RTFM problem? 😀
As explained in readme
Note: you might need

 https://github.com/zhouhan0126/WebServer-esp32

**Comment by vjkanth** [comment]
Somehow missed that line in the FM. Perhaps highlight it bold and different colour from the rest as this seems to be the most important requirement. And yes, successfully compiled and run it. Good experiment, thanks.

**Comment by Ujin74** [comment]
> Проблема с RTFM? 😀 Как объясняется в readme Примечание: возможно, вам понадобится
> 
> https://github.com/zhouhan0126/WebServer-es

Помогло, большое спасибо.
