### ISSUE TITLE
Why can we not use this with the Google Assistant?

### ISSUE THREAD

**Issue by Tejas-MD** [igorantolic/esp32-alexa-wemo-emulator#7]

**Comment by igorantolic** [comment]
I don't see any reason why you would not try to make it work for Google Assistant also.
The community will appreciate it. I am not able to test unless you can donate Google Assistant.

**Comment by Tejas-MD** [comment]
I'm not sure if I can actually add the functionality cause the belkin website says something about account linking for using Google Assistant which is probably why none of the repos can support Google Assistant with their hue/wemo emulation..

I can definitely try testing if your existing repo works with the wemo skill on Google Assistant without any account linking and stuff..

**Comment by igorantolic** [comment]
The trick is to use low security of this protocol so microcontroller lie that it is a device which is actually not true, but solves the challenge to avoid over-the-internet call; rather to be a local call, without complexity. Original authors described better than me here.
Google Assistant might have implemented policy to disallow such calls.

**Comment by igorantolic** [comment]
additional info on https://github.com/igorantolic/esp32-alexa-wemo-emulator/issues/10
