### ISSUE TITLE
Yet another Google Home Question/issue

### ISSUE THREAD

**Issue by griffinmt** [igorantolic/esp32-alexa-wemo-emulator#9]
I have setup, compiled and downloaded to my esp32. I have loaded the wemo app to my android and used it to  add an account for myself. Then went through the steps to add a switch to Google. it scanned for about 30 seconds then announce it was found and to connect to it by going to network settings and look for an ssid starting with wemo. But it never showed up. My phone was within 6 inches of the esp32. SSSOOO close.

**Comment by igorantolic** [comment]
check the answer on https://github.com/igorantolic/esp32-alexa-wemo-emulator/issues/10
